# prefixをCtrl-qに変更（デフォルトはC-b）
set-option -g prefix C-q
unbind-key C-b
bind-key C-q send-prefix

#マウス操作を有効にする
set-option -g mouse-select-pane on
set-option -g mouse-select-window on
set-option -g mouse-resize-pane on

# マウススクロール反映
set-window-option -g mode-mouse on

# 異なるサイズの端末からアクセスした時にリサイズ
setw -g aggressive-resize on

# 256 色対応
set -g default-terminal "xterm-256color"
set -g terminal-overrides "term:colors=256"
set -g display-time 2000

# バインドキーを vi 風に
set-window-option -g mode-keys vi

# 日本語対応
setw -g utf8 on
set -g status-utf8 on

# | でペインを縦分割する
bind | split-window -h

# - でペインを縦分割する
bind - split-window -v

# vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

